title: Sonia Martinot
logo: /images/profile_picture.jpg
description: >-
  Welcome to my website ! 
author:
  name: Sonia Martinot
  email: "sonia.martinot@hotmail.fr"
  linkedin: sonia-martinot-6437a3107
  github: soniamartinot

# theme: jekyll-theme-minimal
theme: minima

minima:
  social_links:
    linkedin: sonia-martinot-6437a3107
    github: soniamartinot
   skin: dark
# minima:
#   skin: dark
