title: Sonia Martinot
logo: /images/profile_picture.jpg
description: >-
  Welcome to my website ! 
author:
  name: Sonia Martinot
  email: "sonia.martinot@hotmail.fr"

theme: jekyll-theme-minimal

jekyll-theme-minimal:
  social_links:
    linkedin: "sonia-martinot-6437a3107"
    github: "soniamartinot"
