title: Sonia Martinot
logo: /images/profile_picture.jpg
description: >-
  Personal website
author:
  name: Sonia Martinot
  email: "sonia.martinot@hotmail.fr"
url: "http://soniamartinot.io"

theme: jekyll-theme-minimal